--- 
apiVersion: v1
kind: Service
metadata: 
  name: drupal-service
spec: 
  ports: 
    - name: http
      nodePort: 30095
      port: 80
      protocol: TCP
  selector: 
    app: drupal
  type: NodePort